name: ReleaseDocumentation

on:
  push:
    branches: [ Release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: RoSharp/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site
        GH_PAT: ${{ secrets.GH_PAT }}
